// RobotBuilder Version: 1.5BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330.commands.autocommands;


import org.usfirst.frc330.commands.breachDefenseCommands.BreachDefenseSelector;

import edu.wpi.first.wpilibj.command.BBCommandGroup;

/**
 *
 */
public class BreachDefense extends BBCommandGroup {
    
    public  BreachDefense() {
    	//Run the breach program for the selected defense
    	addSequential(new BreachDefenseSelector());
    }
}