// RobotBuilder Version: 2.0BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330.commands;

import edu.wpi.first.wpilibj.command.BBCommand;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc330.Robot;
import org.usfirst.frc330.util.Logger.Severity;

/**
 *
 */
public class WaitUntilTeleopConditional extends BBCommand {

    public WaitUntilTeleopConditional() {

    }


    protected void initialize() {
    	if (SmartDashboard.getBoolean("driveHome", false)){
    		Robot.logger.println("Robot done, waiting for teleop", Severity.DEBUG);
    	}
    	else{
    		Robot.logger.println("Returning to start location", Severity.DEBUG);
    	}
    }


    protected void execute() {
    }


    protected boolean isFinished() {
        return SmartDashboard.getBoolean("driveHome", false);
    }


    protected void end() {
    }

    protected void interrupted() {
    }
}
