// RobotBuilder Version: 2.0BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330.subsystems;

import org.usfirst.frc330.Robot;
import org.usfirst.frc330.RobotMap;
import org.usfirst.frc330.constants.ArmConst;
import org.usfirst.frc330.constants.TurretConst;
import org.usfirst.frc330.util.CSVLoggable;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.CANTalon.FeedbackDevice;
import edu.wpi.first.wpilibj.CANTalon.TalonControlMode;
import edu.wpi.first.wpilibj.Preferences;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class Arm extends Subsystem {
	
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon armL = RobotMap.armarmL;
    private final CANTalon armR = RobotMap.armarmR;
    private final Solenoid portcullisWedge = RobotMap.armPortcullisWedge;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    
	/////////////////////////////////////////////////////////////
	// MAIN CLASS
	/////////////////////////////////////////////////////////////
    public Arm() {

    	super();
    	
    	int absolutePosition = armL.getPulseWidthPosition() & 0xFFF; /* mask out the bottom12 bits, we don't care about the wrap arounds */
        /* use the low level API to set the quad encoder signal */
        armL.setEncPosition(absolutePosition - getArmZero());
    	
    	armL.setFeedbackDevice(FeedbackDevice.CtreMagEncoder_Relative);
    	setPIDConstants(ArmConst.proportional, ArmConst.integral, ArmConst.derivative);
    	setArmAbsoluteTolerance(ArmConst.tolerance);
    	setLowerSoftLimit(ArmConst.limitLowerAngle);
    	setUpperSoftLimit(ArmConst.limitUpperAngle);
    	armL.enableForwardSoftLimit(true);
    	armL.enableReverseSoftLimit(true);
    	armL.enableBrakeMode(true);
    	
    	//set armR to follow armL, reversed
    	armR.changeControlMode(TalonControlMode.Follower);
    	armR.set(armL.getDeviceID());
    	armR.reverseOutput(true);
    	
    	SmartDashboard.putData("Arm", armL);
    	
		/////////////////////////////////////////////////////////////////
		// LOG IT!
    	// TODO: Add additional logging as needed
		
		CSVLoggable temp = new CSVLoggable(true) {
			public double get() { return getArmAngle(); }
		};
		Robot.csvLogger.add("ArmAngle", temp);

		temp = new CSVLoggable(true) {
			public double get() { return getArmOutput(); }
		};
		Robot.csvLogger.add("ArmOutput", temp);
		
    }
    
	/////////////////////////////////////////////////////////////
	// GET methods
	/////////////////////////////////////////////////////////////
    
    // Get input from encoder for Arm
    public double getArmAngle()
	{
		return (convertRotationsToDegrees(armL.getPosition()));
	}

	public double getArmOutput() {
		return armL.get();
	}
	
	/////////////////////////////////////////////////////////////
	// SET methods
	/////////////////////////////////////////////////////////////
	/* Set the arm */
    public void setArm(double output) {
    	armL.set(output);
    }
    
    /* Set the arm angle */
    public void setArmAngle(double position) {
    	armL.setSetpoint(convertDegreesToRotations(position));
    }
    
    public void setPIDConstants (double P, double I, double D)
	{
		armL.setPID(P, I, D);
	}
    
    // Quadrants are zero-indexed (0-4)
    // 0 = Lowest; 4 = Highest
    public void setQuadrantPosition(int quadrant)
    {
    	// Grab positioning from arm angle
    	double currentArmAngle = getArmAngle();
    	int currentQuadrant = (int)(currentArmAngle/ArmConst.maxAngleDegrees);
    	
    	if ( quadrant >= ArmConst.minQuadrant && quadrant <= ArmConst.maxQuadrant )
    	{
    		// Set the position
    		SmartDashboard.putNumber("CurrentQuadrant", currentQuadrant);
    		SmartDashboard.putNumber("quadrant", quadrant);
    		armL.setPosition(convertDegreesToRotations(currentArmAngle + (quadrant-currentQuadrant)*ArmConst.maxAngleDegrees));
    	}
    	else
    	{
    		throw new RuntimeException("setQuadrantPosition: Quadrant must be integer value " 
    				+ ArmConst.minQuadrant + "-" + ArmConst.maxQuadrant);
    	}  	
    	
    }
    
	/////////////////////////////////////////////////////////////
	// OTHER Methods (helper functions and commands)
	/////////////////////////////////////////////////////////////
    /* Control the arm manually */
    public void manualArm() {
    	double armCommand = Robot.oi.armJoystick.getY();	
    	double angle;
    	
    	if ( Math.abs(armCommand) > ArmConst.deadZone) {
			if (armL.getControlMode() != TalonControlMode.PercentVbus)
				armL.changeControlMode(TalonControlMode.PercentVbus);
			armL.set(armCommand);
		} else if ( armL.getControlMode() != TalonControlMode.Position) {
			angle = getArmAngle();
			if (angle < ArmConst.limitLowerAngle)
				angle = ArmConst.limitLowerAngle;
			else if (angle > ArmConst.limitUpperAngle)
				angle = ArmConst.limitUpperAngle;

    		armL.changeControlMode(TalonControlMode.Position);
			setArmAngle(angle);
    	} 
    	
    }

    public void stopArm()
	{
		if (armL.isEnabled())
		{
			armL.reset();
		}
		armL.set(0);
	}
    
    public boolean isEnable() {
		return armL.isEnabled();
	}
    
    double tolerance = 0;
    public void setArmAbsoluteTolerance(double absvalue) {
    	tolerance = absvalue;
	}
    
    // Method to Enable Arm
    public void enableArm() {
        armL.enable();
    }
    
    // Method to check if Arm is on target
    public boolean onArmTarget() {
    	double error = convertTicksToDegrees(armL.getClosedLoopError());
        return (Math.abs(error) < tolerance);
    }
    
    public void retractStinger() {
    	portcullisWedge.set(false);
    }
    public void deployStinger() {
    	portcullisWedge.set(true);
    }
    
    public void setArmZero()
	{        
        String name;
        
        if (Robot.isPracticeRobot())
            name = "PracticeArmZero";
        else
            name = "CompetitionArmZero";
        
        Preferences.getInstance().putInt(name, armL.getPulseWidthPosition());
        armL.setEncPosition(0);
    }
    
    public int getArmZero() {
		String name;
        if (Robot.isPracticeRobot())
            name = "PracticeArmZero";
        else
            name = "CompetitionArmZero";
		return Preferences.getInstance().getInt(name,0);
	}
    
    public void setLowerSoftLimit(double lowerAngle) {
    	armL.setReverseSoftLimit(convertDegreesToRotations(lowerAngle));
    }
    
    public void setUpperSoftLimit(double upperAngle) {
    	armL.setForwardSoftLimit(convertDegreesToRotations(upperAngle));
    }
    
    private int convertDegreesToTicks(double degrees) {
    	return (int)(degrees * ArmConst.maxEncoderCounts / ArmConst.maxAngleDegrees);
    }
    
    private double convertTicksToDegrees(int ticks) {
    	return (ticks * ArmConst.maxAngleDegrees / ArmConst.maxEncoderCounts);
    }
    
    private double convertDegreesToRotations(double degrees) {
    	return (degrees / ArmConst.maxAngleDegrees);
    }
    
    private double convertRotationsToDegrees(double rotations) {
    	return (rotations * ArmConst.maxAngleDegrees);
    }
    
    public void monitorArm() {
    	if (Robot.turret.isCentered())
        	setLowerSoftLimit(ArmConst.limitLowerAngle);
    	else
    		setLowerSoftLimit(ArmConst.armSafeLimit);
    		
    }
}
