// RobotBuilder Version: 2.0BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330.subsystems;

import org.usfirst.frc330.Robot;
import org.usfirst.frc330.RobotMap;
import org.usfirst.frc330.commands.*;
import org.usfirst.frc330.constants.ArmConst;
import org.usfirst.frc330.constants.TurretConst;
import org.usfirst.frc330.util.CSVLoggable;

import edu.wpi.first.wpilibj.AnalogPotentiometer;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.CANTalon.StatusFrameRate;
import edu.wpi.first.wpilibj.CANTalon.TalonControlMode;
import edu.wpi.first.wpilibj.PIDController;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;



import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class Arm extends Subsystem {
	
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon armL = RobotMap.armarmL;
    private final CANTalon armR = RobotMap.armarmR;
    private final Solenoid portcullisWedge = RobotMap.armPortcullisWedge;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    
	/////////////////////////////////////////////////////////////
	// MAIN CLASS
	/////////////////////////////////////////////////////////////
    public Arm() {

    	super();
    	
    	setPIDConstants(ArmConst.proportional, ArmConst.integral, ArmConst.derivative);
    	setArmAbsoluteTolerance(ArmConst.tolerance);
    	
    	//set armR to follow armL, reversed
    	armR.changeControlMode(TalonControlMode.Follower);
    	armR.set(armL.getDeviceID());
    	armR.reverseOutput(true);
    	
		/////////////////////////////////////////////////////////////////
		// LOG IT!
    	// TODO: Add additional logging as needed
		
		CSVLoggable temp = new CSVLoggable(true) {
			public double get() { return getArmAngle(); }
		};
		
		Robot.csvLogger.add("ArmAngle", temp);

    }
    
	/////////////////////////////////////////////////////////////
	// GET methods
	/////////////////////////////////////////////////////////////
    
    // Get input from encoder for Arm
    public double getArmAngle()
	{
    	double fetchEncoder = armL.getPosition();
    	double count2deg    = 0.0;
    	 	
    	// NOTES: 
    	// 4096 counts per revolution
    	// 5 revolution of encoder to revolution of arm
    	// TLDR; This means 0-72 degrees = 0-4096 counts
    	
    	count2deg = (ArmConst.maxAngleDegrees * fetchEncoder) / ArmConst.maxEncoderCounts;
    	
		return count2deg;
	}

	public double getArmOutput() {
		return armL.get();
	}
    
	public double pidGet() {
		return getArmAngle();
	}
	
	/////////////////////////////////////////////////////////////
	// SET methods
	/////////////////////////////////////////////////////////////
	/* Set the arm */
    public void setArm(double output) {
    	
    	// Is the turret centered?
    	boolean centered = Robot.turret.getTurretAngle() < TurretConst.turretSafeLimitCW &&
    					   Robot.turret.getTurretAngle() > TurretConst.turretSafeLimitCCW;
    					   
    	//Don't let the arm go down if the turret is not centered
    	if ( !centered && output < 0) {
    		armL.set(0);
    	}
    	/* AHHHH! The arm would eat the ground */
    	else if ( getArmAngle() < ArmConst.limitLowerAngle && output < 0) {
    		armL.set(0);
    	/* OH NOES! The arm would flip off the back of the robot */
    	} else if ( getArmAngle() > ArmConst.limitUpperAngle && output > 0) {
    		armL.set(0);
    	/* We good */
    	} else {
    		armL.set(output);
    	}
    }
    
    /* Set the arm angle */
    public void setArmAngle(double position) {
    	armL.setSetpoint(convertDegreesToRotations(position));
    }
    
    public void setPIDConstants (double P, double I, double D)
	{
		armL.setPID(P, I, D);
	}
    
    // Quadrants are zero-indexed (0-4)
    // 0 = Lowest; 4 = Highest
    public void setQuadrantPosition(int quadrant)
    {
    	// Grab positioning from arm angle
    	double positionRawCount = armL.getPosition();
    	int    tempCtn          = 0;
    	
    	if ( quadrant >= ArmConst.minQuadrant && quadrant <= ArmConst.maxQuadrant )
    	{
    		// Set the position
    		tempCtn = ArmConst.maxEncoderCounts * quadrant;
    		armL.setPosition(positionRawCount + tempCtn);
    	}
    	else
    	{
    		throw new RuntimeException("setQuadrantPosition: Quadrant must be integer value 0-4.");
    	}  	
    	
    }
    
	/////////////////////////////////////////////////////////////
	// OTHER Methods (helper functions and commands)
	/////////////////////////////////////////////////////////////
    /* Control the arm manually */
    public void manualArm() {
    	double tempSetPoint;
    	double armCommand = Robot.oi.armJoystick.getY();	

    	if ( Math.abs(armCommand) > ArmConst.deadZone) {
			if (armL.getControlMode() != TalonControlMode.PercentVbus)
				armL.changeControlMode(TalonControlMode.PercentVbus);
			armL.set(armCommand);
		} else if ( armL.getControlMode() != TalonControlMode.Position) {
    		tempSetPoint = this.getArmAngle();
    		this.setArmAngle(tempSetPoint);
    		armL.changeControlMode(TalonControlMode.Position);
    		armL.enable();
    	}
    	
    }

    public void stopArm()
	{
		if (armL.isEnabled())
		{
			armL.reset();
		}
		armL.set(0);
	}
    
    public boolean isEnable() {
		return armL.isEnabled();
	}
    
    double tolerance = 0;
    public void setArmAbsoluteTolerance(double absvalue) {
    	tolerance = absvalue;
	}
    
    // Method to Enable Arm
    public void enableArm() {
        armL.enable();
    }
    
    // Method to check if Arm is on target
    public boolean onArmTarget() {
    	double error = convertTicksToDegrees(armL.getClosedLoopError());
        return (Math.abs(error) < tolerance);
    }
    
    public void retractStinger() {
    	portcullisWedge.set(false);
    }
    public void deployStinger() {
    	portcullisWedge.set(true);
    }
    
    private int convertDegreesToTicks(double degrees) {
    	return (int)(degrees * 4096.0 / 360.0);
    }
    
    private double convertTicksToDegrees(int ticks) {
    	return (ticks * 360.0 / 4096.0);
    }
    
    private double convertDegreesToRotations(double degrees) {
    	return (degrees / 360.0);
    }
    
    private double convertRotationsToDegrees(double rotations) {
    	return (rotations * 360.0);
    }
}
