// RobotBuilder Version: 2.0BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330.subsystems;

import org.usfirst.frc330.Robot;
import org.usfirst.frc330.RobotMap;
import org.usfirst.frc330.commands.ManualArm;
import org.usfirst.frc330.constants.ArmConst;
import org.usfirst.frc330.util.CSVLoggable;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.CANTalon.FeedbackDevice;
import edu.wpi.first.wpilibj.CANTalon.TalonControlMode;
import edu.wpi.first.wpilibj.Preferences;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class Arm extends Subsystem {
	
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon armL = RobotMap.armarmL;
    private final CANTalon armR = RobotMap.armarmR;
    private final Solenoid portcullisWedge = RobotMap.armPortcullisWedge;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new ManualArm());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    
	/////////////////////////////////////////////////////////////
	// MAIN CLASS
	/////////////////////////////////////////////////////////////
    public Arm() {

    	super();
    	
    	int absolutePosition = armL.getPulseWidthPosition() & 0xFFF; /* mask out the bottom12 bits, we don't care about the wrap arounds */
        /* use the low level API to set the quad encoder signal */
        armL.setEncPosition(absolutePosition - getArmZero());
        //armR.setEncPosition(absolutePosition - getArmZero());
    	
    	armL.setFeedbackDevice(FeedbackDevice.CtreMagEncoder_Relative);
    	armL.reverseSensor(true);
    	armL.reverseOutput(true);
    	setPIDConstants(ArmConst.proportional, ArmConst.integral, ArmConst.derivative);
    	setArmAbsoluteTolerance(ArmConst.tolerance);
    	setLowerSoftLimit(ArmConst.limitLowerAngle);
    	setUpperSoftLimit(ArmConst.limitUpperAngle);
    	armL.enableForwardSoftLimit(false);
    	armL.enableReverseSoftLimit(false);
    	armL.enableBrakeMode(false);
    	
    	//set armR to follow armL, reversed
    	armR.changeControlMode(TalonControlMode.Follower);
    	armR.set(armL.getDeviceID());
    	armR.reverseOutput(true);
    	
    	SmartDashboard.putData("Arm", armL);
    	
		/////////////////////////////////////////////////////////////////
		// LOG IT!
    	// TODO: Add additional logging as needed
		
		CSVLoggable temp = new CSVLoggable(true) {
			public double get() { return getArmAngle(); }
		};
		Robot.csvLogger.add("ArmAngle", temp);

		temp = new CSVLoggable(true) {
			public double get() { return getArmOutput(); }
		};
		Robot.csvLogger.add("ArmOutput", temp);
		
		temp = new CSVLoggable(true) {
			public double get() { return getCurrentQuadrant(); }
		};
		Robot.csvLogger.add("ArmQuadrant", temp);
		
		temp = new CSVLoggable(true) {
			public double get() { return getSetpoint(); }
		};
		Robot.csvLogger.add("ArmSetpoint", temp);
	
		temp = new CSVLoggable(true) {
			public double get() { return getLowerLimit(); }
		};
		Robot.csvLogger.add("LowerLimit", temp);
		
		temp = new CSVLoggable(true) {
			public double get() { return getUpperLimit(); }
		};
		Robot.csvLogger.add("UpperLimit", temp);
		
		temp = new CSVLoggable(true) {
			public double get() { return getLowerLimitTripped() ? 1 : 0; }
		};
		Robot.csvLogger.add("LowerLimitTripped", temp);
		
		temp = new CSVLoggable(true) {
			public double get() { return getUpperLimitTripped() ? 1 : 0; }
		};
		Robot.csvLogger.add("UpperLimitTripped", temp);
    }
    
	/////////////////////////////////////////////////////////////
	// GET methods
	/////////////////////////////////////////////////////////////
    
    // Get input from encoder for Arm
    public double getArmAngle()
	{
		return (convertRotationsToDegrees(armL.getPosition()));
	}
    
    public double getArmPositionTicks()
	{
		return (convertDegreesToTicks(getArmAngle()));
	}
    
    private double lowerLimit = 0;
    public double getLowerLimit()
	{
		return (lowerLimit);
	}
    
    private double upperLimit = 0;
    public double getUpperLimit()
	{
		return (upperLimit);
	}

	public double getArmOutput() {
		return armL.getOutputVoltage()/armL.getBusVoltage();
	}
	
	public boolean getLowerLimitTripped(){
		return (getArmAngle() <= getLowerLimit());
	}
	
	public boolean getUpperLimitTripped(){
		return (getArmAngle() >= getUpperLimit());
	}
	
	/////////////////////////////////////////////////////////////
	// SET methods
	/////////////////////////////////////////////////////////////
	/* Set the arm */
    public void setArm(double output) {
    	
    	if (getLowerLimitTripped() && output > 0)
    		armL.set(0);
    	else if (getUpperLimitTripped() && output < 0)
    		armL.set(0);
    	else
    		armL.set(output);
    }
    
    /* Set the arm angle */
    public void setArmAngle(double position) {
    	if (armL.getControlMode() != TalonControlMode.Position)
    		armL.changeControlMode(TalonControlMode.Position);
    	if (position >= getUpperLimit())
    		position = getUpperLimit();
    	else if (position <= getLowerLimit())
    		position = getLowerLimit();
    	armL.setSetpoint(convertDegreesToRotations(position));
    }
    
    public double getSetpoint() {
    	return convertRotationsToDegrees(armL.getSetpoint());
    }
    
    public void setPIDConstants (double P, double I, double D)
	{
		armL.setPID(P, I, D);
	}
    
    public int getCurrentQuadrant() {
    	return (int)(getArmAngle()/ArmConst.maxAngleDegrees);
    }
    
    // Quadrants are zero-indexed (0-4)
    // 0 = Lowest; 4 = Highest
    public void setQuadrantPosition(int quadrant)
    {
    	// Grab positioning from arm angle
    	double currentArmAngle = getArmAngle();
    	int currentQuadrant = getCurrentQuadrant();
    	double angleChange = (quadrant-currentQuadrant)*ArmConst.maxAngleDegrees;
    	
    	if ( quadrant >= ArmConst.minQuadrant && quadrant <= ArmConst.maxQuadrant )
    	{
    		// Set the position
    		Robot.logger.println("Original Quadrant: " + currentQuadrant, true);
    		Robot.logger.println("New Quadrant: " + quadrant, true);
    		armL.setPosition(convertDegreesToRotations(currentArmAngle + angleChange));
    		setArmAngle(getArmAngle() + angleChange);
    	}
    	else
    	{
    		throw new RuntimeException("setQuadrantPosition: Quadrant must be integer value " 
    				+ ArmConst.minQuadrant + "-" + ArmConst.maxQuadrant);
    	}  	
    	
    }
    
	/////////////////////////////////////////////////////////////
	// OTHER Methods (helper functions and commands)
	/////////////////////////////////////////////////////////////
    /* Control the arm manually */
    public void manualArm() {
    	double armCommand = -Robot.oi.armJoystick.getY();	
    	
    	if ( Math.abs(armCommand) > ArmConst.deadZone) {
			if (armL.getControlMode() != TalonControlMode.PercentVbus)
				armL.changeControlMode(TalonControlMode.PercentVbus);
			setArm(armCommand);
			Robot.logger.println("Set: " + armCommand);
		} 
    	else if ( armL.getControlMode() != TalonControlMode.Position) {

    		armL.changeControlMode(TalonControlMode.Position);
			setArmAngle(getArmAngle());
    	} 
    	
    }

    public void stopArm()
	{
		if (armL.isEnabled())
		{
			armL.reset();
			armL.changeControlMode(TalonControlMode.Position);
			armL.enable();
		}
		armL.set(0);
	}
    
    public boolean isEnable() {
		return armL.isEnabled();
	}
    
    double tolerance = 0;
    public void setArmAbsoluteTolerance(double absvalue) {
    	tolerance = absvalue;
	}
    
    // Method to Enable Arm
    public void enableArm() {
        armL.enable();
    }
    
    // Method to check if Arm is on target
    public boolean onArmTarget() {
    	double error = convertTicksToDegrees(armL.getClosedLoopError());
        return (Math.abs(error) < tolerance);
    }
    
    public void retractStinger() {
    	portcullisWedge.set(false);
    }
    public void deployStinger() {
    	portcullisWedge.set(true);
    }
    
    public void setArmZero()
	{        
        String name;
        
        if (Robot.isPracticeRobot())
            name = "PracticeArmZero";
        else
            name = "CompetitionArmZero";
        
        Preferences.getInstance().putInt(name, armL.getPulseWidthPosition());
        armL.setEncPosition(0);
        armR.setEncPosition(0);
    }
    
    public int getArmZero() {
		String name;
        if (Robot.isPracticeRobot())
            name = "PracticeArmZero";
        else
            name = "CompetitionArmZero";
		return Preferences.getInstance().getInt(name,0);
	}
    
    private void setLowerSoftLimit(double lowerAngle) {
    	lowerLimit = lowerAngle;
    }
    
    private void setUpperSoftLimit(double upperAngle) {
    	upperLimit = upperAngle;
    }
    
    private int convertDegreesToTicks(double degrees) {
    	return (int)(degrees * ArmConst.maxEncoderCounts / ArmConst.maxAngleDegrees);
    }
    
    private double convertTicksToDegrees(int ticks) {
    	return (ticks * ArmConst.maxAngleDegrees / ArmConst.maxEncoderCounts);
    }
    
    private double convertDegreesToRotations(double degrees) {
    	return (degrees / ArmConst.maxAngleDegrees);
    }
    
    private double convertRotationsToDegrees(double rotations) {
    	return (rotations * ArmConst.maxAngleDegrees);
    }
    
    public void monitorArm() {
    	if (Robot.turret.isCentered())
        	setLowerSoftLimit(ArmConst.limitLowerAngle);
    	else
    		setLowerSoftLimit(ArmConst.armSafeLimit);
    	if (Robot.arm.getArmAngle() <= ArmConst.armSafeLimit)
    		Robot.turret.setSoftLimitsSafe();
    	else
    		Robot.turret.setSoftLimitsArmUp();
    }
}
